---
name: Thread-Const
version: 0.003
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Constant strings efficiently shared between threads
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Thread-Const
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/thread-const/tree
build_requires:
  Test::More: 0
requires:
  File::Map: 0
  Sub::Exporter: 0
  perl: 5.008
configure_requires:
  Module::Build: 0.340201
provides:
  Thread::Const:
    file: lib/Thread/Const.pm
    version: 0.003
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - mmap
  - threads
  - sharing
  - read-only
  - readonly
