---
name: Thread-Const
version: 0.001
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Constant strings efficiently shared between threads
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Thread-Const
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/thread-const/tree
requires:
  Data::Swap: 0
  Exporter: 5.57
  File::Map: 0
  Readonly: 1.03
  perl: 5.008
build_requires:
  Test::More: 0
provides:
  Thread::Const:
    file: lib/Thread/Const.pm
    version: 0.001
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - mmap
  - threads
  - sharing
  - read-only
  - readonly
